<?php

/**
 * PluginPluginPackage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class PluginPluginPackage extends BasePluginPackage
{
  public function getImageFilename()
  {
    return (string)$this->getImage();
  }

  public function getLeadMemberIds()
  {
    return array(1);
  }

  public function getMembers($limit = null, $isRandom = false)
  {
    $q = Doctrine::getTable('PluginMember')->createQuery()
      ->where('package_id = ?', $this->id);

    if (!is_null($limit))
    {
      $q->limit($limit);
    }

    if ($isRandom)
    {
      $expr = new Doctrine_Expression('RANDOM()');
      $q->orderBy($expr);
    }

    $members = $q->execute();
    if (!$members->count())
    {
      return false;
    }

    $q = Doctrine::getTable('Member')->createQuery()
      ->whereIn('id', array_values($members->toKeyValueArray('id', 'member_id')));

    return $q->execute();
  }

  public function countMembers()
  {
    return Doctrine::getTable('PluginMember')
      ->createQuery()
      ->where('package_id = ?', array($this->id))
      ->count();
  }

  public function countUsers()
  {
    return Doctrine::getTable('PluginUser')
      ->createQuery()
      ->where('package_id = ?', array($this->id))
      ->count();
  }

  public function isUser($id)
  {
    return (bool)$this->getUser($id);
  }

  public function getUser($id)
  {
    return Doctrine::getTable('PluginUser')
      ->createQuery()
      ->where('package_id = ?', array($this->id))
      ->where('member_id = ?', array($id))
      ->fetchOne();
  }

  public function toggleUsing($id)
  {
    if ($user = $this->getUser($id))
    {
      $user->delete();
    }
    else
    {
      $this->PluginUser[]->member_id = $id;
      $this->save();
    }
  }
}
